import { SignIn, SignInButton } from "@clerk/nextjs";
import styles from "./index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
// import Link from "next/link";

// import { api } from "~/utils/api";

const Home: NextPage = () => {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="btn-container">
      <SignInButton mode="modal">
        
        <button className="btn">Sign in</button>
        
      </SignInButton>
      </div>
      <main className={styles.main}>
        <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
      </main>
    </>
  );
};

export default Home;
